/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import Author.AuthorPanel;
import Books.BooksPanel;
import Borrow.BorrowedPanel;
import Default.FeaturePanel;
import Publisher.PublisherPanel;
import Default.StaticAccess;
import Member.MemberPanel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author keno
 */
public final class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    PublisherPanel publishPanel;
    AuthorPanel authorPanel;
    MemberPanel memberPanel;
    BooksPanel booksPanel;
    BorrowedPanel borrowedPanel;
    FeaturePanel featurePanel;

    public HomePage() {
        initComponents();
        this.setTitle("Library-homepage");
        this.setExtendedState(HomePage.MAXIMIZED_BOTH);
        displayScrollPane.getVerticalScrollBar().setUnitIncrement(16);        
        createPanel();
        displayTree.setSelectionRow(0);
    }

    void createPanel() {
        publishPanel = new PublisherPanel();
        authorPanel = new AuthorPanel();
        memberPanel = new MemberPanel();
        booksPanel = new BooksPanel();
        borrowedPanel = new BorrowedPanel();
        featurePanel = new FeaturePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayTree = new javax.swing.JTree();
        displayScrollPane = new javax.swing.JScrollPane();
        displayPNL = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("LIBRARY");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("PUBLISH");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("AUTHOR");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("MEMBER");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BOOKS");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BORROWED BY");
        treeNode1.add(treeNode2);
        displayTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        displayTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                displayTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(displayTree);

        displayPNL.setLayout(new java.awt.BorderLayout());
        displayScrollPane.setViewportView(displayPNL);

        jMenu1.setText("Connection");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Re-connect");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Close");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayScrollPane)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        StaticAccess.closeWindow(this);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new database.DatabaseConnectionClass();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void displayTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_displayTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) displayTree.getLastSelectedPathComponent();

        if (node == null) {
            return;
        }
        String nodeText = node.toString();
        if (node.isLeaf()) {
            displayPNL.removeAll();

            switch (nodeText) {
                case "PUBLISH":
                    displayPNL.add(publishPanel);
                    break;
                case "AUTHOR":
                    displayPNL.add(authorPanel);
                    break;
                case "MEMBER":
                    displayPNL.add(memberPanel);
                    break;
                case "BOOKS":
                    displayPNL.add(booksPanel);
                    break;
                case "BORROWED BY":
                    displayPNL.add(borrowedPanel);
                    break;
            }

            displayPNL.revalidate();
            displayPNL.repaint();


        } else {
            displayPNL.add(featurePanel);
            displayPNL.revalidate();
            displayPNL.repaint();

        }
    }//GEN-LAST:event_displayTreeValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPNL;
    private javax.swing.JScrollPane displayScrollPane;
    private javax.swing.JTree displayTree;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
